### ISSUE TITLE
Команды без базового состава не должны попадать в релиз через три месяца после начала сезона

### ISSUE THREAD

**Issue by razumau** [maii-chgk/rating-b#18]
https://www.maii.li/docs/2021-08-30-polozhenie-ob-egide-i-rejtinge-maii
А.2.2. В релиз Рейтинга вносятся команды:

имеющие на момент релиза БС на текущий сезон или имевшие БС в прошлом сезоне, но пока не сформировавшие его в текущем (в течение первых трёх месяцев с начала сезона) — для них рассчитываются места в соответствии с пунктом А.3.7

**Comment by chernov1985** [comment]
Оказалось, у нас не подгружены БС команд, которые в нынешнем сезоне не сыграли ни одной игры в рейтинг. Юрий этим занимается.

**Comment by razumau** [comment]
Теперь базовые составы всех команд есть (для команд без игр в рейтинг пока есть только обновление раз в неделю). Выгрузка базовых для всех 86 тысяч команд заняла четыре с половиной часа.

**Comment by chernov1985** [comment]
Fixed in https://github.com/maii-chgk/rating-b/commit/6a9a174bff481082fdab18986d5dc44b5b194e05
