### ISSUE TITLE
Некоторые TRB вычисляются как 0, хотя у игроков БС ненулевые рейтинги

### ISSUE THREAD

**Issue by gltronred** [maii-chgk/rating-b#28]
Например, у команды ["Эчпочмак, маца, мацун"](https://rating.chgk.info/teams/86648/history) регулярно в качестве TRB возвращается 0 (например, в релизе от 22 декабря, см. также скриншот)

![image](https://user-images.githubusercontent.com/308836/226276830-d2279469-a5ec-430c-be5d-c83708d97032.png)

Эта ошибка именно в расчёте TRB, поскольку API рейтинга МАИИ выдаёт `trb = 0` (см. приложенный t1.json):
```
    {
      "place": 458,
      "team_id": 86648,
      ...
      "release_id": 69,
      "trb": 0,
      ...
    },
```

При этом TRB команды не может быть равен нулю, поскольку в соответствии с [A.3.11](https://www.maii.li/p/aegis-rating#a311), он должен вычисляться как "сумма рейтингов шести наиболее высокорейтинговых игроков, отсортированных по убыванию рейтинга с коэффициентами 1, 5/6, 2/3, 1/2, 1/3, 1/6", и рейтинги игроков БС не равны нулю:
- игрок 115539 - рейтинг 11610 (p1.json)
- игрок 74413 - рейтинг 12281 (p1.json)
- игрок 55949 - рейтинг 10854 (p2.json)
- игрок 175104 - рейтинг 11679 (p1.json)
- игрок 38696 - рейтинг 9269 (p4.json)
- игрок 32807 - рейтинг 11324 (p1.json)

Из-за этого бага, очевидно, в некоторых релизах неправильно рассчитывается коэффициент Q, связывающий индивидуальный и командный рейтинги.

Приложен [архив с ответами API](https://github.com/maii-chgk/rating-b/files/11015447/api-responses.zip), выданными около 10:40 мск 20 марта 2023 на запросы:
- t1.json - https://rating.maii.li/api/v1/b/teams/69.json?page=1
- p1.json - https://rating.maii.li/api/v1/b/players/69.json?page=1
- p2.json - https://rating.maii.li/api/v1/b/players/69.json?page=2
- p3.json - https://rating.maii.li/api/v1/b/players/69.json?page=3
- p4.json - https://rating.maii.li/api/v1/b/players/69.json?page=4

**Comment by razumau** [comment]
Во время синка данных с rating.chgk.info в базу рейтинга мы пропускали все команды без базовых составов. Это приводило к тому, что игрок мог оказаться в базовом составе двух команд одновременно:
1. Игрока Х добавляют в состав команды А.
2. Мы записываем этот состав в базу рейтинга.
3. Оказывается, что представитель по ошибке создал команду А, и игроков этой команды переносят в состав команды B, оставляя команду А пустой.
4. При следующем синке мы записываем игрока Х в команду В, но ничего не делаем с командой А, ведь у неё теперь нет базовых составов.
5. Игрок Х теперь находится в базовом двух команд.

В коде расчёта рейтинга есть (ошибочная, в будущем будет убрана) попытка выбрать в таких случаях один из этих составов: https://github.com/maii-chgk/rating-b/blob/b194aaf6c2d114d84e53574d5f2cbd662bd4f725/scripts/db_tools.py#L35. Когда `start_date` для обоих составов одинаковая, результат сортировки случаен, и при каждом пересчёте в базовом составе команды B оказывалось случайное количество игроков, что сильно меняло технический рейтинг базового состава.

Этот баг в импорте теперь исправлен: https://github.com/maii-chgk/rating-importer/pull/10. Все случаи (около 25 игроков) в базе тоже пофикшены, релизы пересчитаны.

В результате некоторые команды заметно поднялись:
[Газлайтинг Львумбы](https://rating.chgk.info/teams/86649): 60 → 35
[Эчпочмак, маца, мацун](https://rating.chgk.info/teams/86648): 166 → 48
[Конец света с последующим симпозиумом](https://rating.chgk.info/teams/86884): 150 → 115
